#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 12
#define STATE_COUNT 57
#define LARGE_STATE_COUNT 28
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 4

enum {
  sym_comment = 1,
  anon_sym_COLON_EQ = 2,
  anon_sym_SEMI = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_null = 6,
  anon_sym_true = 7,
  anon_sym_false = 8,
  sym_integer = 9,
  sym_string = 10,
  sym_symbol = 11,
  anon_sym_LBRACK = 12,
  anon_sym_COMMA = 13,
  anon_sym_RBRACK = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  anon_sym_COLON = 17,
  sym_identifier = 18,
  anon_sym_EQ_GT = 19,
  sym_source_file = 20,
  sym_declaration = 21,
  sym__statement = 22,
  sym_expression_statement = 23,
  sym__expression = 24,
  sym_parenthesized = 25,
  sym__literal = 26,
  sym_boolean = 27,
  sym_list = 28,
  sym_map = 29,
  sym_entry = 30,
  sym_block = 31,
  sym_call = 32,
  sym_function = 33,
  sym_field = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_list_repeat1 = 36,
  aux_sym_map_repeat1 = 37,
  aux_sym_block_repeat1 = 38,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_COLON_EQ] = ":=",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_null] = "null",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_integer] = "integer",
  [sym_string] = "string",
  [sym_symbol] = "symbol",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_identifier] = "identifier",
  [anon_sym_EQ_GT] = "=>",
  [sym_source_file] = "source_file",
  [sym_declaration] = "declaration",
  [sym__statement] = "_statement",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym_parenthesized] = "parenthesized",
  [sym__literal] = "_literal",
  [sym_boolean] = "boolean",
  [sym_list] = "list",
  [sym_map] = "map",
  [sym_entry] = "entry",
  [sym_block] = "block",
  [sym_call] = "call",
  [sym_function] = "function",
  [sym_field] = "field",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_integer] = sym_integer,
  [sym_string] = sym_string,
  [sym_symbol] = sym_symbol,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_identifier] = sym_identifier,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [sym_source_file] = sym_source_file,
  [sym_declaration] = sym_declaration,
  [sym__statement] = sym__statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym_parenthesized] = sym_parenthesized,
  [sym__literal] = sym__literal,
  [sym_boolean] = sym_boolean,
  [sym_list] = sym_list,
  [sym_map] = sym_map,
  [sym_entry] = sym_entry,
  [sym_block] = sym_block,
  [sym_call] = sym_call,
  [sym_function] = sym_function,
  [sym_field] = sym_field,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_argument = 1,
  field_body = 2,
  field_declaration = 3,
  field_entry = 4,
  field_expression = 5,
  field_function = 6,
  field_item = 7,
  field_key = 8,
  field_map = 9,
  field_name = 10,
  field_parameter = 11,
  field_statement = 12,
  field_value = 13,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_body] = "body",
  [field_declaration] = "declaration",
  [field_entry] = "entry",
  [field_expression] = "expression",
  [field_function] = "function",
  [field_item] = "item",
  [field_key] = "key",
  [field_map] = "map",
  [field_name] = "name",
  [field_parameter] = "parameter",
  [field_statement] = "statement",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[25] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 2},
  [13] = {.index = 17, .length = 1},
  [14] = {.index = 18, .length = 1},
  [15] = {.index = 19, .length = 1},
  [16] = {.index = 20, .length = 1},
  [17] = {.index = 21, .length = 2},
  [18] = {.index = 23, .length = 1},
  [19] = {.index = 24, .length = 2},
  [20] = {.index = 26, .length = 2},
  [21] = {.index = 28, .length = 2},
  [22] = {.index = 30, .length = 2},
  [23] = {.index = 32, .length = 2},
  [24] = {.index = 34, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_declaration, 0},
  [1] =
    {field_declaration, 0, .inherited = true},
  [2] =
    {field_declaration, 0, .inherited = true},
    {field_declaration, 1, .inherited = true},
  [4] =
    {field_statement, 0},
  [5] =
    {field_name, 0},
    {field_value, 2},
  [7] =
    {field_key, 1},
    {field_map, 0},
  [9] =
    {field_argument, 1},
    {field_function, 0},
  [11] =
    {field_expression, 1},
  [12] =
    {field_item, 0},
  [13] =
    {field_item, 1},
  [14] =
    {field_item, 1, .inherited = true},
  [15] =
    {field_item, 0, .inherited = true},
    {field_item, 1, .inherited = true},
  [17] =
    {field_expression, 0},
  [18] =
    {field_entry, 0},
  [19] =
    {field_entry, 1},
  [20] =
    {field_entry, 1, .inherited = true},
  [21] =
    {field_entry, 0, .inherited = true},
    {field_entry, 1, .inherited = true},
  [23] =
    {field_statement, 1, .inherited = true},
  [24] =
    {field_statement, 0, .inherited = true},
    {field_statement, 1, .inherited = true},
  [26] =
    {field_body, 2},
    {field_parameter, 0},
  [28] =
    {field_item, 1, .inherited = true},
    {field_item, 2},
  [30] =
    {field_key, 0},
    {field_value, 2},
  [32] =
    {field_entry, 1, .inherited = true},
    {field_entry, 2},
  [34] =
    {field_expression, 2},
    {field_statement, 1, .inherited = true},
};

static TSSymbol ts_alias_sequences[25][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '(') ADVANCE(10);
      if (lookahead == ')') ADVANCE(11);
      if (lookahead == ',') ADVANCE(20);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '=') ADVANCE(2);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead == ']') ADVANCE(21);
      if (lookahead == 'f') ADVANCE(25);
      if (lookahead == 'n') ADVANCE(34);
      if (lookahead == 't') ADVANCE(31);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == '=') ADVANCE(8);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 5},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 5},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(56),
    [sym_declaration] = STATE(53),
    [aux_sym_source_file_repeat1] = STATE(49),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
  },
  [2] = {
    [sym_declaration] = STATE(43),
    [sym__statement] = STATE(43),
    [sym_expression_statement] = STATE(43),
    [sym__expression] = STATE(14),
    [sym_parenthesized] = STATE(14),
    [sym__literal] = STATE(14),
    [sym_boolean] = STATE(14),
    [sym_list] = STATE(14),
    [sym_map] = STATE(14),
    [sym_entry] = STATE(51),
    [sym_block] = STATE(14),
    [sym_call] = STATE(14),
    [sym_function] = STATE(14),
    [sym_field] = STATE(14),
    [aux_sym_map_repeat1] = STATE(7),
    [aux_sym_block_repeat1] = STATE(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(11),
    [sym_string] = ACTIONS(15),
    [sym_symbol] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
  },
  [3] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_null] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [sym_integer] = ACTIONS(27),
    [sym_string] = ACTIONS(25),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_COLON] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
  },
  [4] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_COLON] = ACTIONS(31),
    [sym_identifier] = ACTIONS(37),
  },
  [5] = {
    [sym_declaration] = STATE(43),
    [sym__statement] = STATE(43),
    [sym_expression_statement] = STATE(43),
    [sym__expression] = STATE(15),
    [sym_parenthesized] = STATE(15),
    [sym__literal] = STATE(15),
    [sym_boolean] = STATE(15),
    [sym_list] = STATE(15),
    [sym_map] = STATE(15),
    [sym_block] = STATE(15),
    [sym_call] = STATE(15),
    [sym_function] = STATE(15),
    [sym_field] = STATE(15),
    [aux_sym_block_repeat1] = STATE(6),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(39),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(39),
    [sym_string] = ACTIONS(41),
    [sym_symbol] = ACTIONS(41),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(43),
    [sym_identifier] = ACTIONS(23),
  },
  [6] = {
    [sym_declaration] = STATE(43),
    [sym__statement] = STATE(43),
    [sym_expression_statement] = STATE(43),
    [sym__expression] = STATE(21),
    [sym_parenthesized] = STATE(21),
    [sym__literal] = STATE(21),
    [sym_boolean] = STATE(21),
    [sym_list] = STATE(21),
    [sym_map] = STATE(21),
    [sym_block] = STATE(21),
    [sym_call] = STATE(21),
    [sym_function] = STATE(21),
    [sym_field] = STATE(21),
    [aux_sym_block_repeat1] = STATE(6),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(45),
    [anon_sym_null] = ACTIONS(48),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_integer] = ACTIONS(48),
    [sym_string] = ACTIONS(54),
    [sym_symbol] = ACTIONS(54),
    [anon_sym_LBRACK] = ACTIONS(57),
    [anon_sym_LBRACE] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(63),
    [sym_identifier] = ACTIONS(65),
  },
  [7] = {
    [sym__expression] = STATE(19),
    [sym_parenthesized] = STATE(19),
    [sym__literal] = STATE(19),
    [sym_boolean] = STATE(19),
    [sym_list] = STATE(19),
    [sym_map] = STATE(19),
    [sym_entry] = STATE(50),
    [sym_block] = STATE(19),
    [sym_call] = STATE(19),
    [sym_function] = STATE(19),
    [sym_field] = STATE(19),
    [aux_sym_map_repeat1] = STATE(8),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(68),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(68),
    [sym_string] = ACTIONS(70),
    [sym_symbol] = ACTIONS(70),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(72),
    [sym_identifier] = ACTIONS(37),
  },
  [8] = {
    [sym__expression] = STATE(19),
    [sym_parenthesized] = STATE(19),
    [sym__literal] = STATE(19),
    [sym_boolean] = STATE(19),
    [sym_list] = STATE(19),
    [sym_map] = STATE(19),
    [sym_entry] = STATE(55),
    [sym_block] = STATE(19),
    [sym_call] = STATE(19),
    [sym_function] = STATE(19),
    [sym_field] = STATE(19),
    [aux_sym_map_repeat1] = STATE(8),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(74),
    [anon_sym_null] = ACTIONS(77),
    [anon_sym_true] = ACTIONS(80),
    [anon_sym_false] = ACTIONS(80),
    [sym_integer] = ACTIONS(77),
    [sym_string] = ACTIONS(83),
    [sym_symbol] = ACTIONS(83),
    [anon_sym_LBRACK] = ACTIONS(86),
    [anon_sym_LBRACE] = ACTIONS(89),
    [anon_sym_RBRACE] = ACTIONS(92),
    [sym_identifier] = ACTIONS(94),
  },
  [9] = {
    [sym__expression] = STATE(12),
    [sym_parenthesized] = STATE(12),
    [sym__literal] = STATE(12),
    [sym_boolean] = STATE(12),
    [sym_list] = STATE(12),
    [sym_map] = STATE(12),
    [sym_block] = STATE(12),
    [sym_call] = STATE(12),
    [sym_function] = STATE(12),
    [sym_field] = STATE(12),
    [aux_sym_list_repeat1] = STATE(10),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(97),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(97),
    [sym_string] = ACTIONS(99),
    [sym_symbol] = ACTIONS(99),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(101),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [10] = {
    [sym__expression] = STATE(17),
    [sym_parenthesized] = STATE(17),
    [sym__literal] = STATE(17),
    [sym_boolean] = STATE(17),
    [sym_list] = STATE(17),
    [sym_map] = STATE(17),
    [sym_block] = STATE(17),
    [sym_call] = STATE(17),
    [sym_function] = STATE(17),
    [sym_field] = STATE(17),
    [aux_sym_list_repeat1] = STATE(10),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(103),
    [anon_sym_null] = ACTIONS(106),
    [anon_sym_true] = ACTIONS(109),
    [anon_sym_false] = ACTIONS(109),
    [sym_integer] = ACTIONS(106),
    [sym_string] = ACTIONS(112),
    [sym_symbol] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(115),
    [anon_sym_RBRACK] = ACTIONS(118),
    [anon_sym_LBRACE] = ACTIONS(120),
    [sym_identifier] = ACTIONS(123),
  },
  [11] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(126),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(126),
    [sym_identifier] = ACTIONS(37),
  },
  [12] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_RBRACK] = ACTIONS(130),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [13] = {
    [sym__expression] = STATE(16),
    [sym_parenthesized] = STATE(16),
    [sym__literal] = STATE(16),
    [sym_boolean] = STATE(16),
    [sym_list] = STATE(16),
    [sym_map] = STATE(16),
    [sym_block] = STATE(16),
    [sym_call] = STATE(16),
    [sym_function] = STATE(16),
    [sym_field] = STATE(16),
    [aux_sym_list_repeat1] = STATE(9),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(132),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(132),
    [sym_string] = ACTIONS(134),
    [sym_symbol] = ACTIONS(134),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_RBRACK] = ACTIONS(136),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [14] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(138),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(140),
    [sym_identifier] = ACTIONS(37),
  },
  [15] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(138),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_RBRACE] = ACTIONS(142),
    [sym_identifier] = ACTIONS(37),
  },
  [16] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_RBRACK] = ACTIONS(144),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [17] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_COMMA] = ACTIONS(128),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [18] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_RPAREN] = ACTIONS(146),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [19] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_COLON] = ACTIONS(140),
    [sym_identifier] = ACTIONS(37),
  },
  [20] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(148),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [21] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(138),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [22] = {
    [sym__expression] = STATE(3),
    [sym_parenthesized] = STATE(3),
    [sym__literal] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_list] = STATE(3),
    [sym_map] = STATE(3),
    [sym_block] = STATE(3),
    [sym_call] = STATE(3),
    [sym_function] = STATE(3),
    [sym_field] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [anon_sym_SEMI] = ACTIONS(150),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(33),
    [sym_string] = ACTIONS(35),
    [sym_symbol] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [23] = {
    [sym__expression] = STATE(22),
    [sym_parenthesized] = STATE(22),
    [sym__literal] = STATE(22),
    [sym_boolean] = STATE(22),
    [sym_list] = STATE(22),
    [sym_map] = STATE(22),
    [sym_block] = STATE(22),
    [sym_call] = STATE(22),
    [sym_function] = STATE(22),
    [sym_field] = STATE(22),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(152),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(152),
    [sym_string] = ACTIONS(154),
    [sym_symbol] = ACTIONS(154),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [24] = {
    [sym__expression] = STATE(11),
    [sym_parenthesized] = STATE(11),
    [sym__literal] = STATE(11),
    [sym_boolean] = STATE(11),
    [sym_list] = STATE(11),
    [sym_map] = STATE(11),
    [sym_block] = STATE(11),
    [sym_call] = STATE(11),
    [sym_function] = STATE(11),
    [sym_field] = STATE(11),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(156),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(156),
    [sym_string] = ACTIONS(158),
    [sym_symbol] = ACTIONS(158),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [25] = {
    [sym__expression] = STATE(18),
    [sym_parenthesized] = STATE(18),
    [sym__literal] = STATE(18),
    [sym_boolean] = STATE(18),
    [sym_list] = STATE(18),
    [sym_map] = STATE(18),
    [sym_block] = STATE(18),
    [sym_call] = STATE(18),
    [sym_function] = STATE(18),
    [sym_field] = STATE(18),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(160),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(160),
    [sym_string] = ACTIONS(162),
    [sym_symbol] = ACTIONS(162),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [26] = {
    [sym__expression] = STATE(4),
    [sym_parenthesized] = STATE(4),
    [sym__literal] = STATE(4),
    [sym_boolean] = STATE(4),
    [sym_list] = STATE(4),
    [sym_map] = STATE(4),
    [sym_block] = STATE(4),
    [sym_call] = STATE(4),
    [sym_function] = STATE(4),
    [sym_field] = STATE(4),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(164),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(164),
    [sym_string] = ACTIONS(166),
    [sym_symbol] = ACTIONS(166),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
  [27] = {
    [sym__expression] = STATE(20),
    [sym_parenthesized] = STATE(20),
    [sym__literal] = STATE(20),
    [sym_boolean] = STATE(20),
    [sym_list] = STATE(20),
    [sym_map] = STATE(20),
    [sym_block] = STATE(20),
    [sym_call] = STATE(20),
    [sym_function] = STATE(20),
    [sym_field] = STATE(20),
    [sym_comment] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_null] = ACTIONS(168),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_integer] = ACTIONS(168),
    [sym_string] = ACTIONS(170),
    [sym_symbol] = ACTIONS(170),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [sym_identifier] = ACTIONS(37),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_EQ_GT,
    ACTIONS(174), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(172), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [27] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(178), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [51] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(182), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [75] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(186), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [99] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(190), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [123] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(194), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [147] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(198), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(202), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [195] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(206), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [219] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(210), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(214), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [267] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(218), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [291] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(222), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [315] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(226), 11,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [339] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_EQ_GT,
    ACTIONS(230), 1,
      anon_sym_COLON_EQ,
    ACTIONS(174), 6,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      anon_sym_COLON,
      sym_identifier,
    ACTIONS(172), 7,
      anon_sym_SEMI,
      anon_sym_LPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [366] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(232), 6,
      anon_sym_LPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(236), 6,
      anon_sym_LPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [404] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(240), 6,
      anon_sym_LPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [423] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(244), 6,
      anon_sym_LPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [442] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 5,
      anon_sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_integer,
      sym_identifier,
    ACTIONS(248), 6,
      anon_sym_LPAREN,
      sym_string,
      sym_symbol,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [461] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
    ACTIONS(254), 1,
      sym_identifier,
    STATE(48), 1,
      aux_sym_source_file_repeat1,
    STATE(53), 1,
      sym_declaration,
  [477] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(257), 1,
      ts_builtin_sym_end,
    STATE(48), 1,
      aux_sym_source_file_repeat1,
    STATE(53), 1,
      sym_declaration,
  [493] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(261), 1,
      anon_sym_RBRACE,
  [503] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_COMMA,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
  [513] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [529] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_COLON_EQ,
  [536] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(259), 1,
      anon_sym_COMMA,
  [543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(28)] = 0,
  [SMALL_STATE(29)] = 27,
  [SMALL_STATE(30)] = 51,
  [SMALL_STATE(31)] = 75,
  [SMALL_STATE(32)] = 99,
  [SMALL_STATE(33)] = 123,
  [SMALL_STATE(34)] = 147,
  [SMALL_STATE(35)] = 171,
  [SMALL_STATE(36)] = 195,
  [SMALL_STATE(37)] = 219,
  [SMALL_STATE(38)] = 243,
  [SMALL_STATE(39)] = 267,
  [SMALL_STATE(40)] = 291,
  [SMALL_STATE(41)] = 315,
  [SMALL_STATE(42)] = 339,
  [SMALL_STATE(43)] = 366,
  [SMALL_STATE(44)] = 385,
  [SMALL_STATE(45)] = 404,
  [SMALL_STATE(46)] = 423,
  [SMALL_STATE(47)] = 442,
  [SMALL_STATE(48)] = 461,
  [SMALL_STATE(49)] = 477,
  [SMALL_STATE(50)] = 493,
  [SMALL_STATE(51)] = 503,
  [SMALL_STATE(52)] = 513,
  [SMALL_STATE(53)] = 521,
  [SMALL_STATE(54)] = 529,
  [SMALL_STATE(55)] = 536,
  [SMALL_STATE(56)] = 543,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call, 2, .production_id = 7),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call, 2, .production_id = 7),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3, .production_id = 20),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, .production_id = 19), SHIFT_REPEAT(25),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, .production_id = 19), SHIFT_REPEAT(21),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, .production_id = 19), SHIFT_REPEAT(36),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, .production_id = 19), SHIFT_REPEAT(21),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, .production_id = 19), SHIFT_REPEAT(13),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, .production_id = 19), SHIFT_REPEAT(2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, .production_id = 19),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, .production_id = 19), SHIFT_REPEAT(42),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 17), SHIFT_REPEAT(25),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 17), SHIFT_REPEAT(19),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 17), SHIFT_REPEAT(36),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 17), SHIFT_REPEAT(19),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 17), SHIFT_REPEAT(13),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 17), SHIFT_REPEAT(2),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 17),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 17), SHIFT_REPEAT(28),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(25),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(17),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(36),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(17),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(13),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(2),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 12), SHIFT_REPEAT(28),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 3, .production_id = 22),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, .production_id = 6),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 2, .production_id = 6),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, .production_id = 18),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, .production_id = 18),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, .production_id = 10),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, .production_id = 10),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, .production_id = 11),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, .production_id = 11),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized, 3, .production_id = 8),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized, 3, .production_id = 8),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, .production_id = 24),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, .production_id = 24),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4, .production_id = 23),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 4, .production_id = 23),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, .production_id = 21),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4, .production_id = 21),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, .production_id = 15),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, .production_id = 15),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, .production_id = 16),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, .production_id = 16),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 2),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 2),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, .production_id = 4),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 1, .production_id = 4),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 9),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_list_repeat1, 2, .production_id = 9),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 14),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 14),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 2, .production_id = 13),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 2, .production_id = 13),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4, .production_id = 5),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 4, .production_id = 5),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, .production_id = 3), SHIFT_REPEAT(54),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, .production_id = 2),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, .production_id = 1),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [269] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_quench(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const uint16_t *)ts_parse_table,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .field_count = FIELD_COUNT,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .field_names = ts_field_names,
    .large_state_count = LARGE_STATE_COUNT,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .state_count = STATE_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
