import Immutable from "https://example.com/quench.js";
const $my_null = null;
const $my_boolean = true;
const $my_other_boolean = false;
const $my_int = 4;
const $my_negative_int = -3;
const $my_string = "hello";
const $my_symbol = Symbol.for("hi_there");
const $my_list = Immutable.List([1, "yes", 3, false]);
const $my_empty_list = Immutable.List([]);
const $my_map = Immutable.Map([[Symbol.for("foo"), 42], [Immutable.List([Symbol.for("baz"), null]), Symbol.for("qux")], ["bar", Immutable.List([-8, Immutable.Map([]), 10, Immutable.List([])])]]);
const $my_empty_map = Immutable.Map([]);
const $my_nested_map = Immutable.Map([[Symbol.for("cat"), Immutable.Map([[Symbol.for("dog"), "bird"]])]]);
const $main = $_ => (() => {
  console.log("my_int:");
  console.log($my_int);
  console.log("");
  console.log("my_list[3]:");
  console.log($my_list.get(3));
  console.log("");
  console.log("my_map.foo:");
  console.log($my_map.get(Symbol.for("foo")));
  console.log("");
  console.log("my_map deep item:");
  console.log($my_map.get("bar").get(2));
  console.log("");
  console.log("my_nested_map.cat.dog:");
  console.log($my_nested_map.get(Symbol.for("cat")).get(Symbol.for("dog")));
})();
$main();
