import * as Immutable from "https://deno.land/x/immutable@4.0.0-rc.12/node_modules/immutable/dist/immutable.es.js";
var my_null = null;
var my_boolean = true;
var my_other_boolean = false;
var my_int = BigInt("42");
var my_negative_int = BigInt("-3");
var my_string = "hello";
var my_symbol = Symbol.for("hi_there");
var my_list = Immutable.List([BigInt("1"), "yes", BigInt("3"), false]);
var my_empty_list = Immutable.List([]);
var my_map = Immutable.Map([[Symbol.for("foo"), BigInt("42")], [Immutable.List([Symbol.for("baz"), null]), Symbol.for("qux")], ["bar", Immutable.List([BigInt("-8"), Immutable.Map([]), BigInt("10"), Immutable.List([])])]]);
var my_empty_map = Immutable.Map([]);
